services:
  - type: web
    name: postflow-ai-backend
    env: docker
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postflow-ai-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

databases:
  - name: postflow-ai-db
    databaseName: postflow
    user: postflow
    plan: free
